/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.koneksi;
/**
 *
 * @author Kelar_Gaye
 */
public class Login extends javax.swing.JFrame {
    String user="",pass="";
private final Connection conn = new koneksi().connect();    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(getRootPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tPassword = new javax.swing.JPasswordField();
        tUsername = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        login = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 640));
        getContentPane().setLayout(null);
        getContentPane().add(tPassword);
        tPassword.setBounds(290, 470, 350, 40);
        getContentPane().add(tUsername);
        tUsername.setBounds(290, 370, 350, 40);

        register.setBackground(new java.awt.Color(0, 204, 51));
        register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(500, 530, 140, 40);

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BT1-LOGIN.png"))); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(300, 530, 140, 40);

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(790, 20, 80, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1HAL LOGIN.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 900, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    try {
            java.sql.Statement stat = conn.createStatement();
            String sql = "SELECT * FROM login WHERE username = '"+tUsername.getText()+
            "' and password = '"+tPassword.getText()+"'";
            //java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if (rs.next())
            {               
                if(tUsername.getText().equals(rs.getString("username"))&&tPassword.getText().equals(rs.getString("password"))&&rs.getString("hakAkses").equals("Staff")){
                     JOptionPane.showMessageDialog(null,"Login Berhasil, Halo Staff!");
                    new dashboard().setVisible(true);
                    dispose();
                }else if(tUsername.getText().equals(rs.getString("username"))&&tPassword.getText().equals(rs.getString("password"))&&rs.getString("hakAkses").equals("Manager")){
                    JOptionPane.showMessageDialog(null,"Login Berhasil, Halo Manager!");
                    new barang().setVisible(true);
                    dispose();
                }else if(tUsername.getText().equals(rs.getString("username"))&&tPassword.getText().equals(rs.getString("password"))&&rs.getString("hakAkses").equals("Admin")){
                     JOptionPane.showMessageDialog(null,"Login Berhasil, Halo Admin!");
                    new dashboard().setVisible(true);
                    dispose();}
            }
            }catch (Exception e){
                { System.out.print(e.getMessage());}
            }
                
//               if (pass.equals(pass) && user.equals(user)){
//                    JOptionPane.showMessageDialog(this, "Login Berhasil");
//                    //UserSession.setUserLogin(status);
//
//                    if(status.equals("staff")){
//                        dashboard mu=new dashboard();
//                        mu.setVisible(true);
//                        dispose();
//                    }
//                    else if(status.equals("manager")){
//                        dashboard mu=new dashboard();
//                        mu.setVisible(true);
//                        dispose();
//                    }
//                    else{
//                        dashboard MainFrame = new dashboard();
//                        MainFrame.setVisible(true);
//                        dispose();
//                    }
//                }
//            
//                else
//                JOptionPane.showMessageDialog(null, "Username atau Password anda salah");
//            }
//            else
//            JOptionPane.showMessageDialog(this, "Username Tidak Ada");
//        }catch (Exception e){
//            JOptionPane.showMessageDialog(null, "Ada Kesalahan");
//        }
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        new register().setVisible(true);
            dispose();
    }//GEN-LAST:event_registerActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton exit;
    private javax.swing.JButton login;
    private javax.swing.JButton register;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
